package com.cahcap.common.util;

import com.cahcap.common.block.MultiblockPartBlock;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import net.minecraft.core.Direction;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.VoxelShape;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.Map;

/**
 * Data-driven multiblock collision shapes.
 * Loads per-position VoxelShapes from JSON generated by datagen,
 * then precomputes rotated and mirrored variants for all 4 facings.
 * <p>
 * Also serves as the single source of truth for multiblock axis ranges
 * and coordinate conversion between blueprint space (SOUTH default)
 * and model space (NORTH default).
 */
public class MultiblockShapes {

    private final VoxelShape[] northShapes;
    private final VoxelShape[][] byFacing;
    private final VoxelShape[][] byFacingMirrored;

    private final int dxMin, dyMin, dzMin;
    private final int dxMax, dyMax, dzMax;
    private final int xSize, ySize, zSize;

    private MultiblockShapes(VoxelShape[] northShapes,
                             int dxMin, int dyMin, int dzMin,
                             int xSize, int ySize, int zSize) {
        this.northShapes = northShapes;
        this.dxMin = dxMin;
        this.dyMin = dyMin;
        this.dzMin = dzMin;
        this.dxMax = dxMin + xSize - 1;
        this.dyMax = dyMin + ySize - 1;
        this.dzMax = dzMin + zSize - 1;
        this.xSize = xSize;
        this.ySize = ySize;
        this.zSize = zSize;

        this.byFacing = MultiblockPartBlock.precomputeRotatedShapes(northShapes);
        this.byFacingMirrored = MultiblockPartBlock.precomputeMirroredShapes(northShapes, i -> {
            int dy = i / (xSize * zSize);
            int dx = (i % (xSize * zSize)) / zSize;
            int dz = i % zSize;
            int mirroredDx = (xSize - 1) - dx;
            return dy * xSize * zSize + mirroredDx * zSize + dz;
        });
    }

    // ==================== Axis Ranges (Model Space) ====================

    /** Total number of block positions in this multiblock. */
    public int totalPositions() { return xSize * ySize * zSize; }

    public int dxMin() { return dxMin; }
    public int dyMin() { return dyMin; }
    public int dzMin() { return dzMin; }
    public int dxMax() { return dxMax; }
    public int dyMax() { return dyMax; }
    public int dzMax() { return dzMax; }
    public int xSize() { return xSize; }
    public int ySize() { return ySize; }
    public int zSize() { return zSize; }

    // ==================== Coordinate Conversion ====================

    /**
     * Convert model-space offset (NORTH-oriented) to position index.
     * Index formula: (dy - dyMin) * xSize * zSize + (dx - dxMin) * zSize + (dz - dzMin)
     */
    public int toIndex(int dx, int dy, int dz) {
        return (dy - dyMin) * xSize * zSize + (dx - dxMin) * zSize + (dz - dzMin);
    }

    /**
     * Convert position index to model-space offset (NORTH-oriented).
     * @return [dx, dy, dz]
     */
    public int[] fromIndex(int index) {
        int yzSlice = xSize * zSize;
        int dy = index / yzSlice + dyMin;
        int rem = index % yzSlice;
        int dx = rem / zSize + dxMin;
        int dz = rem % zSize + dzMin;
        return new int[]{dx, dy, dz};
    }

    /**
     * Convert blueprint-space offset (SOUTH default) to model-space offset (NORTH default).
     * The two coordinate systems are 180° apart: negate X and Z.
     */
    public static int[] blueprintToModel(int bpDx, int bpDy, int bpDz) {
        return new int[]{-bpDx, bpDy, -bpDz};
    }

    /**
     * Convert model-space offset (NORTH default) to blueprint-space offset (SOUTH default).
     * Same operation as blueprintToModel (self-inverse).
     */
    public static int[] modelToBlueprint(int modelDx, int modelDy, int modelDz) {
        return new int[]{-modelDx, modelDy, -modelDz};
    }

    // ==================== Shape Lookup ====================

    /**
     * Look up the shape for a given world offset, facing, and mirror state.
     */
    public VoxelShape get(Direction facing, int[] offset, boolean mirrored) {
        int[] model = MultiblockPartBlock.worldToModelOffset(facing, offset);
        int dx = model[0] - dxMin;
        int dy = model[1] - dyMin;
        int dz = model[2] - dzMin;

        if (dx < 0 || dx >= xSize || dy < 0 || dy >= ySize || dz < 0 || dz >= zSize) {
            return Shapes.block();
        }

        int index = dy * xSize * zSize + dx * zSize + dz;
        if (index < 0 || index >= northShapes.length) {
            return Shapes.block();
        }

        VoxelShape[][] table = mirrored ? byFacingMirrored : byFacing;
        return table[facing.get2DDataValue()][index];
    }

    // ==================== Loading ====================

    /**
     * Load shapes from a JSON resource on the classpath.
     *
     * @param resourcePath classpath path, e.g. "/assets/herbalcurative/voxelshapes/cauldron.json"
     */
    public static MultiblockShapes load(String resourcePath) {
        String clPath = resourcePath.startsWith("/") ? resourcePath.substring(1) : resourcePath;

        InputStream is = null;
        try {
            is = Thread.currentThread().getContextClassLoader().getResourceAsStream(clPath);
            if (is == null) {
                is = MultiblockShapes.class.getResourceAsStream(resourcePath);
            }
            if (is == null) {
                is = ClassLoader.getSystemResourceAsStream(clPath);
            }
            if (is == null) {
                // During datagen the JSON hasn't been generated yet — return a stub
                return new MultiblockShapes(new VoxelShape[]{Shapes.block()}, 0, 0, 0, 1, 1, 1);
            }
            JsonObject root = JsonParser.parseReader(new InputStreamReader(is, StandardCharsets.UTF_8)).getAsJsonObject();
            return fromJson(root);
        } catch (Exception e) {
            throw new RuntimeException("Failed to load voxelshapes from " + resourcePath, e);
        } finally {
            if (is != null) {
                try { is.close(); } catch (Exception ignored) {}
            }
        }
    }

    private static MultiblockShapes fromJson(JsonObject root) {
        // Read axis ranges from metadata (authoritative source)
        JsonObject axisRanges = root.getAsJsonObject("axis_ranges");
        int dxMin, dxMax, dyMin, dyMax, dzMin, dzMax;

        if (axisRanges != null) {
            dxMin = axisRanges.get("dx_min").getAsInt();
            dxMax = axisRanges.get("dx_max").getAsInt();
            dyMin = axisRanges.get("dy_min").getAsInt();
            dyMax = axisRanges.get("dy_max").getAsInt();
            dzMin = axisRanges.get("dz_min").getAsInt();
            dzMax = axisRanges.get("dz_max").getAsInt();
        } else {
            // Fallback: infer from shape keys (legacy compatibility)
            dxMin = Integer.MAX_VALUE; dxMax = Integer.MIN_VALUE;
            dyMin = Integer.MAX_VALUE; dyMax = Integer.MIN_VALUE;
            dzMin = Integer.MAX_VALUE; dzMax = Integer.MIN_VALUE;
            JsonObject shapesObj = root.getAsJsonObject("shapes");
            for (String key : shapesObj.keySet()) {
                String[] parts = key.split(",");
                int dx = Integer.parseInt(parts[0]), dy = Integer.parseInt(parts[1]), dz = Integer.parseInt(parts[2]);
                dxMin = Math.min(dxMin, dx); dxMax = Math.max(dxMax, dx);
                dyMin = Math.min(dyMin, dy); dyMax = Math.max(dyMax, dy);
                dzMin = Math.min(dzMin, dz); dzMax = Math.max(dzMax, dz);
            }
        }

        int xSize = dxMax - dxMin + 1;
        int ySize = dyMax - dyMin + 1;
        int zSize = dzMax - dzMin + 1;
        int totalSize = xSize * ySize * zSize;

        VoxelShape[] northShapes = new VoxelShape[totalSize];
        for (int i = 0; i < totalSize; i++) {
            northShapes[i] = Shapes.empty();
        }

        JsonObject shapesObj = root.getAsJsonObject("shapes");
        for (Map.Entry<String, JsonElement> entry : shapesObj.entrySet()) {
            String[] parts = entry.getKey().split(",");
            int dx = Integer.parseInt(parts[0]) - dxMin;
            int dy = Integer.parseInt(parts[1]) - dyMin;
            int dz = Integer.parseInt(parts[2]) - dzMin;
            int index = dy * xSize * zSize + dx * zSize + dz;

            JsonArray boxes = entry.getValue().getAsJsonArray();
            VoxelShape shape = Shapes.empty();
            for (JsonElement boxEl : boxes) {
                JsonArray box = boxEl.getAsJsonArray();
                shape = Shapes.or(shape, Block.box(
                        box.get(0).getAsDouble(), box.get(1).getAsDouble(), box.get(2).getAsDouble(),
                        box.get(3).getAsDouble(), box.get(4).getAsDouble(), box.get(5).getAsDouble()));
            }
            northShapes[index] = shape;
        }

        return new MultiblockShapes(northShapes, dxMin, dyMin, dzMin, xSize, ySize, zSize);
    }
}
